version: '3.7'

services:
  web:
    build: .
    env_file:
      - config/.env.development

    command: python /app/onlineshop/manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/app
    ports:
      - 8000:8000
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq 

  redis:
    image: redis
    env_file:
      - .env 
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis_data:/data
volumes:
  postgres_data:
  rabbitmq_data:
  redis_data: